### ISSUE TITLE
HDMI In not working 

### ISSUE THREAD

**Issue by josephmangmang** [zidootech/ZidooDigitalSignage#15]
Device : Zidoo Z9X

None of the build apks are working. 

```
2021-11-26 14:25:07.086 3752-11723/com.zidoo.rtk.hdmi D/AudioRxEncoder: [notifyHotplug][HDMIRx] state: 1
2021-11-26 14:25:07.086 3752-17517/com.zidoo.rtk.hdmi D/RtkMediaCodecPlayer: [onMessageReceived][HDMIRx] kWhatHDMIRxVideoHotplug state:1
2021-11-26 14:25:07.086 3752-17516/com.zidoo.rtk.hdmi D/RtkHDMIRxManager-JNI: [HDMIRx] receive kWhatHDMIRxVideoHotplug 307
2021-11-26 14:25:07.087 3752-17516/com.zidoo.rtk.hdmi D/RtkHDMIRxManager: native event 2
2021-11-26 14:25:07.087 3752-3752/com.zidoo.rtk.hdmi V/hdmi_bob: RecorderInterface onReceive hdmiRxPlugged = true
2021-11-26 14:25:07.087 3752-3752/com.zidoo.rtk.hdmi V/hdmi_bob: initResolution isConnnect = true
2021-11-26 14:25:07.087 3752-17518/com.zidoo.rtk.hdmi E/CameraRecorder: call camera connect at kWhatGetCameraParam, should not reach here under service mode
2021-11-26 14:25:07.103 3752-17518/com.zidoo.rtk.hdmi W/CameraBase: An error occurred while connecting to camera 0: Status(-8): '1: connectHelper:1388: No permission to open camera "/dev/video250"'
2021-11-26 14:25:07.104 3752-3752/com.zidoo.rtk.hdmi E/RtkHDMIRxManager: getParameters Error: java.lang.RuntimeException: getParameters failed (empty parameters)
2021-11-26 14:25:07.105 3752-3752/com.zidoo.rtk.hdmi W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
2021-11-26 14:25:07.106 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at com.zidoo.rtk.hdmi.recorder.listener.RecorderInterface.initResolution(RecorderInterface.java:475)
2021-11-26 14:25:07.106 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at com.zidoo.rtk.hdmi.recorder.listener.RecorderInterface.onEvent(RecorderInterface.java:551)
2021-11-26 14:25:07.106 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at com.realtek.hardware.RtkHDMIRxManager$1.run(RtkHDMIRxManager.java:87)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at android.os.Looper.loop(Looper.java:193)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2021-11-26 14:25:07.107 3752-3752/com.zidoo.rtk.hdmi W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

other crash

```
2021-11-26 14:32:40.273 17345-17345/MY_PACKAGE_ID E/AndroidRuntime: FATAL EXCEPTION: main
    Process: MY_PACKAGE_ID, PID: 17345
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/MY_PACKAGE_ID-fegfTIeObDro0F_d4FZQMQ==/base.apk"],nativeLibraryDirectories=[/data/app/MY_PACKAGE_ID-fegfTIeObDro0F_d4FZQMQ==/lib/arm, /data/app/MY_PACKAGE_ID-fegfTIeObDro0F_d4FZQMQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]] couldn't find "librealtek_runtime.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.realtek.hardware.RtkHDMIRxManager.<clinit>(RtkHDMIRxManager.java:31)
        at MY_PACKAGE_ID.views.zido.ZidooHdmiDisPlay.play(ZidooHdmiDisPlay.java:184)
        at MY_PACKAGE_ID.views.zido.ZidooHdmiDisPlay.startDisPlay(ZidooHdmiDisPlay.java:345)
        at MY_PACKAGE_ID.views.zido.HDMIActivity.onResume(HDMIActivity.java:63)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-11-26 14:32:44.360 2223-2868/system_process W/ActivityManager:   Force finishing activity MY_PACKAGE_ID/.views.zido.HDMIActivity
2021-11-26 14:32:44.469 2223-2319/system_process W/InputDispatcher: channel 'e1ccbeb MY_PACKAGE_ID/MY_PACKAGE_ID.views.zido.HDMIActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2021-11-26 14:32:44.469 2223-2319/system_process E/InputDispatcher: channel 'e1ccbeb MY_PACKAGE_ID/MY_PACKAGE_ID.views.zido.HDMIActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-11-26 14:32:44.476 2223-7478/system_process I/WindowManager: WIN DEATH: Window{e1ccbeb u0 MY_PACKAGE_ID/MY_PACKAGE_ID.views.zido.HDMIActivity}
2021-11-26 14:32:44.476 2223-7478/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'e1ccbeb MY_PACKAGE_ID/MY_PACKAGE_IDviews.zido.HDMIActivity (server)'
2021-11-26 14:32:44.484 1819-2290/? W/SurfaceFlinger: Attempting to set client state on removed layer: MY_PACKAGE_IDy/MY_PACKAGE_ID.views.zido.HDMIActivity#0
2021-11-26 14:32:44.485 1819-2290/? W/SurfaceFlinger: Attempting to destroy on removed layer: MY_PACKAGE_ID/MY_PACKAGE_ID.views.zido.HDMIActivity#0
```

**Comment by zidootech** [comment]
For Z9X Z10 Pro, Z1000 Pro, please refer to the [ZidooDigitalSignage_v3](https://github.com/zidootech/ZidooDigitalSignage_v3) project.

**Comment by josephmangmang** [comment]
Thank you @zidootech
